[build]
  publish = "dist"
  command = "yarn run generate"
  functions = "./functions"

[context.production.environment]
  BASE_URL = "https://ux.xyz"

[[plugins]]
package = "@netlify/plugin-sitemap"

[functions."mailchimp-digest"]
#schedule = "@weekly"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
